blank_issues_enabled: false
contact_links:
  - name: Translation
    url: https://hosted.weblate.org/projects/antennapod/
    about: To correct or add translations we invite you to help us out on Weblate.
  - name: Feedback or suggestion
    url: https://forum.antennapod.org/
    about: If the above don't fit, please leave your feedback on our forum
